# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 'Assessing-International-Diversity-Conferences'

# Title of the Site
title: Assessing the International Diversity of Computer Science Conferences
# Description of the Site
description: "This project aims to assess the international diversity of computer science conferences by analyzing the geographical distribution of authors and institutions of top-tier conferences."
# URL of Image of the Site
site-image: /assets/images/Decoration/Main.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/Decoration/icon_v2.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/Decoration/Main.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: marinalopezalet@gmail.com
#facebook_username: /
#twitter_username: /
#instagram_username: /
linkedin_username: marina-lópez-alet
github_username:  Marina-LA
#youtube_channel_id: /
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
#disqus-shortname: thedevslot

# Name of the Author
author-name: Marina López Alet
# URL for the Image of the Author
author-image: https://avatars.githubusercontent.com/u/140148145?v=4
# 60 Words About the Author
author-about: I am a researcher in Cloud and Distributed Systems Lab at the Universitat Rovira i Virgili. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Marina-LA

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
#permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
